### ISSUE TITLE
Web form for adding user and assign tasks (bundles)

### ISSUE THREAD

**Issue by FredrikKarlssonSpeech** [humlab-speech/visible-speech-deployment#101]

**Comment by liasam92** [comment]
A suggestion:

- new button on start page: "Members/ tasks" (remove button "Access/members")
- When clicking the Members/task button a new page is loaded (same tab or new?)
- The new page has two tabs. Tab 1 is active on default

**Tab 1 – List/ add members**
- List project members (like in GitLab) 
- Add new member (name, role, and expiration date as in Git). 

**Tab 2 – List assignees/ reassign**
- List assignees: a list of all sessions and bundles in the VISPDB, and which member is currently assigned to each bundle. There is also a "reassign"-button in each row.
- Reassign bundle/session: user clicks on the Reassign-button -> a popup displays all project members in a list. The user clicks on a member to reassign that bundle -> pop-up closes. 
A thought: If possible, we should allow the project leader to reassign an entire session (i.e. automatically reassign all bundles included in that session).
- Save button: saves any changes made

**Comment by johanvonboer** [comment]
The default bundlelist should also be named after the user who created the project, not "user.user".
