### ISSUE TITLE
Webapp crashes when adding a new session to an existing database

### ISSUE THREAD

**Issue by liasam92** [humlab-speech/visible-speech-deployment#104]
Not sure where the problem lies, but when adding av new session, weapp returns the following error message
`Error validating / checking DBconfig: { "message": "Additional properties not allowed", "code": 303, "dataPath": "/metadataDefaults", "schemaPath": "/additionalProperties", "subErrors": null, "stack": "Error: Additional properties not allowed\n at new d (https://emu-webapp.visp.humlab.umu.se/dist/emuwebapp.bundle.js:40:31698)\n at i.createError (https://emu-webapp.visp.humlab.umu.se/dist/emuwebapp.bundle.js:40:13563)\n at i.validateObjectProperties (https://emu-webapp.visp.humlab.umu.se/dist/emuwebapp.bundle.js:40:25236)\n at i.validateObject (https://emu-webapp.visp.humlab.umu.se/dist/emuwebapp.bundle.js:40:23579)\n at i.validateAll (https://emu-webapp.visp.humlab.umu.se/dist/emuwebapp.bundle.js:40:17792)\n at Object.validate (https://emu-webapp.visp.humlab.umu.se/dist/emuwebapp.bundle.js:40:32833)\n at e.validateJSO (https://emu-webapp.visp.humlab.umu.se/dist/emuwebapp.bundle.js:181:452588)\n at https://emu-webapp.visp.humlab.umu.se/dist/emuwebapp.bundle.js:181:295466\n at e.invoke (https://emu-webapp.visp.humlab.umu.se/dist/emuwebapp.bundle.js:97:7006)\n at t.run (https://emu-webapp.visp.humlab.umu.se/dist/emuwebapp.bundle.js:97:2205)" }`

No ssff-files are created
User_bundlelist looks ok
metadata file is created

**Comment by FredrikKarlssonSpeech** [comment]
Oh. I wonder when the Emu Web app started checking this? 

This is an issue (at least in part) caused by metadata being set on the database level. Please move the metadata into all sessions instead for now ?

I will send an issue to the web app developers so that they may ignore the field "metadataDefaults" in the JSON.

**Comment by liasam92** [comment]
A question: Is "Age" supposed to be a number or a string? I've been messing around with the add_metadata function, and I've lost track of all the changes I've managed to make ;)

**Comment by FredrikKarlssonSpeech** [comment]
Age should be a number. If it is a string, many things may fail at the moment.

**Comment by FredrikKarlssonSpeech** [comment]
If this is only an issue with "metadataDefaults" being rejected by the client, then the issue has been reported to the webapp project:

https://github.com/IPS-LMU/EMU-webApp/issues/302

**Comment by FredrikKarlssonSpeech** [comment]
Fixed in 
https://github.com/humlab-speech/reindeer/commit/490a0e21ade763392a5555b715a8d69880cafd1c

@johanvonboer @TomasSkotare  Please use the newest version of reindeer.
