### ISSUE TITLE
Add session - no ssff files are created

### ISSUE THREAD

**Issue by liasam92** [humlab-speech/visible-speech-deployment#105]
For function "add session", check the following:

1. Create ssff-files from .wav(s) and metadata "Gender" and "Age"
2. Check that metadata are added the same way as when creating a new project, i.e. Gender = Female, Male or NULL; Age= numerical value or NULL

**Comment by FredrikKarlssonSpeech** [comment]
@johanvonboer Should be fixed now in reindeer. Please install the last committed version.

**Comment by johanvonboer** [comment]
Fixed
