### ISSUE TITLE
Metadata:Age - should be a numerical value or NULL

### ISSUE THREAD

**Issue by liasam92** [humlab-speech/visible-speech-deployment#106]
Not sure if this causes problems with Fredriks add signal function?

**Comment by FredrikKarlssonSpeech** [comment]
Yes! Please set it to null if the string returned from the form is "" @johanvonboer

**Comment by liasam92** [comment]
and otherwise set a numerical value, e.g. 47 instead of "47"?

**Comment by johanvonboer** [comment]
This is now fixed. Age is always a number or null.
