### ISSUE TITLE
Add session with track file generation fails

### ISSUE THREAD

**Issue by johanvonboer** [humlab-speech/visible-speech-deployment#108]
This is what I get when trying to add a session to a project and generate ssff-files for this new session with the add_trackDefinition function:
`Error in add_trackDefinition(VISPDB, name = \"FORMANTS\", onTheFlyFunctionName = \"forest\") : \n  A track named 'FORMANTS' is already defined, but with a differend columnName and fileExtension, and this function can therefore not define the SSFF track you as requested.`

**Comment by FredrikKarlssonSpeech** [comment]
Yep. I am on it.

**Comment by johanvonboer** [comment]
Just realized this is (at least partly) a duplicate of https://github.com/humlab-speech/visible-speech-deployment/issues/105

**Comment by FredrikKarlssonSpeech** [comment]
Duplicate
