### ISSUE TITLE
Random activation/deactivation of button Create project

### ISSUE THREAD

**Issue by liasam92** [humlab-speech/visible-speech-deployment#110]
The Create project button is activated as soon as the field _Project name_ is filled in.
However, audio files should be mandatory (see issue #109 ), and there seems to be some confusion as to whether Documentation is expected or not.

As it is now, Documentation is sometimes mandatory and sometimes not. 
If I don't add any new annotation levels or links, I can create a new project without adding anything to _Documentation_ (Image 1). But if I add something, I can't create the project unless I add something to _Documentation_ (Image 2).

Image 1
![Skärmavbild 2021-12-27 kl  11 04 26](https://user-images.githubusercontent.com/63298177/147460978-3268b5b9-309f-4af0-959e-f215e9eea333.png)

Image 2
![Skärmavbild 2021-12-27 kl  11 05 02](https://user-images.githubusercontent.com/63298177/147460997-c3ee6f5b-61c4-484e-97ff-5ff0a4d8fde6.png)

**Comment by FredrikKarlssonSpeech** [comment]
Seems solved.
