### ISSUE TITLE
Enhance upload performance

### ISSUE THREAD

**Issue by johanvonboer** [humlab-speech/visible-speech-deployment#113]
Uploading files is slow. Try to make it faster.

**Comment by FredrikKarlssonSpeech** [comment]
I attach some sound files for testing. The smaller 5 minute file takes ~30 seconds to upload. 
The larger 10minute file takes a long time. I stopped the timer after 12 minutes.

[sinefiles.zip](https://github.com/humlab-speech/visible-speech-deployment/files/7979812/sinefiles.zip)

**Comment by johanvonboer** [comment]
I have now updated visp with some changes regarding uploads (this is what caused the recent outage - sorry about that).

Uploads were previously done by base64-encoding the binary wav files and then uploading them in that format. This was not very efficient, it was just the simplest/fastest way for me to do it when I originally built this. So I changed that to now instead uploading the file in its raw/binary form, which should speed up uploads a little bit, not sure exactly how much, I would guess around 30%.

I also experimented with zipping the wav files before upload, and there's support for this now in the client. Initially it showed promise when I experimented on a 700kb wav file which were compressed to 264k using level 1 (fastest) compression which took 339ms to complete. However later testing on other larger wavs - after I had already implemented the feature - showed that for most of them it seems to take longer than it is worth in terms of size decrease vs time spent. So I disabled the feature.

I did also briefly look at using a WASM module for doing the zipping, since this should be a lot faster than native js zipping, but ran into some problems and decided not to spend the hours on trying to sort them out right now. I also saw someone somewhere say that transferring files from js memory to wasm memory is very slow and would thus negate the speedup, don't know if this is true or not.

We could however still use the serverside part of this feature by allowing uploads wav files the user has already zipped themselves. But I haven't so far activated that either since allowing uploads of zip files strongly implies (imo) that you could also upload a zip containing multiple wavs, and there's no support for that right now, but should be easy to implement.

**Comment by johanvonboer** [comment]
These changes are not on the server yet, but just writing for future reference before I forget, that I have now enabled uploads of zipped files (as in the user can drop zipped files - not that the client itself zips them, it doesn't). The zip archive may contain multiple files. The backend will clean out any non-wav files inside the zip and simply discard them, it will also try to flatten any subdirectories, but won't go deeper than 1 directory down.

**Comment by johanvonboer** [comment]
This is now live on the server.

**Comment by FredrikKarlssonSpeech** [comment]
Uploading is much more efficient now, but maybe #121 is somehow related to the fix of this issue?
