### ISSUE TITLE
Importing sound files creates sessions but no bundles

### ISSUE THREAD

**Issue by FredrikKarlssonSpeech** [humlab-speech/visible-speech-deployment#117]
I cannot determine right now if this issue is located in reindeer or in VISP, but I have just manually imported files using the web interface and I have session directories corresponding to my imports, but no bundles (no bundle dir and no sound files and so on..)(.

What do the logs say @johanvonboer ?

**Comment by johanvonboer** [comment]
They don't say very much other than that we received an empty POST request... I don't have this problem myself (unfortunately), perhaps it's something with the files you are uploading? Anything strange with their format? Or just really many and very large ones? How big is the largest one?

**Comment by FredrikKarlssonSpeech** [comment]
No, really not. 

Its a mix of single files of about 2-4 MB each
```
> du -m *.wav
4	K10.wav
3	K11.wav
3	K12.wav
3	K13.wav
4	K14.wav
3	K3.wav
3	K4.wav
3	K5.wav
4	K6.wav
3	K7.wav
4	K8.wav
4	M1.wav
3	M10.wav
3	M11.wav
4	M12.wav
3	M13.wav
4	M14.wav
2	M15.wav
3	M16.wav
3	M17.wav
3	M18.wav
2	M3.wav
3	M4.wav
4	M5.wav
3	M6.wav
4	M7.wav
2	M8.wav
4	M9.wav
```

and then collections of small files that together are about 1-2 MBs:

```
> du -m 
1	./M10_80
2	./M1_137
1	./M2_91
2	./M1_100
1	./M5_214
1	./M8_79
1	./F10_134
2	./M11_130
1	./F3_201
1	./M7_91
1	./M8_129
1	./F9_160
1	./F5_97
2	./M6_100
1	./M12_137
2	./F5_124
1	./F8_120
1	./M5_170
2	./M6_123
1	./M12_178
2	./F1_152
2	./M2_114
1	./F2_110
1	./F1_116
1	./F1_172
1	./F3_174
2	./F5_144
1	./F4_119
2	./F7_144
1	./M9_115
1	./F7_117
1	./M11_79
1	./F2_99
1	./M10_119
1	./F4_158
1	./M7_129
2	./M9_153
1	./M4_110
1	./F10_179
1	./M3_202
1	./F8_77
```

Odd.

**Comment by FredrikKarlssonSpeech** [comment]
I can reproduce this issue in other projects too, old projects as well as newly created ones. Sound files, and signal files then, are consistently not saved / creates on recording import.

**Comment by FredrikKarlssonSpeech** [comment]
@johanvonboer the issue seems to be have been introduced I Safari only. In Chrome, you can add files to the session created while you create a project. You can also add new sessions to that project then in chrome. 

In safari, the media file disappears when you create a project and initial session. The same thing happens if you add a session. 

It also seems to be the case that Safari-created projects cannot be added to via the interface from chrome, which is a bit odd, and I need to verify it. 

I also managed to loose larger files, but I also need to check that this issue was not only present in safari-created projects.

**Comment by johanvonboer** [comment]
Interesting, do you get any errors in the browser console?

**Comment by FredrikKarlssonSpeech** [comment]
Seems resolved
