### ISSUE TITLE
The creation of a new container never finishes for a new project

### ISSUE THREAD

**Issue by FredrikKarlssonSpeech** [humlab-speech/visible-speech-deployment#121]
If you try to create a new project now, the process of creating a container never finishes.

The same on both Chrome and Safari

https://user-images.githubusercontent.com/200246/154911320-3f8a020d-b663-433e-b034-8b47f92369b2.mov

**Comment by johanvonboer** [comment]
Fixed. Turns out that one of the "old and unused" directory mounts for this container that I thought was garbage and had cleaned out earlier was not so unused after all...
