### ISSUE TITLE
IPs are not correctly tracked in Matomo

### ISSUE THREAD

**Issue by TomasSkotare** [humlab-speech/visible-speech-deployment#128]
Due to load balacing / possibly firewall and other infrastucture, the reported IP for users are local IPs instead of their real IPs.

It is unclear if this causes enough data loss to be problematic, as we cannot determine the country of origin for visitors. However, from a GDPR point of view, it is advantageous.

Consider if this is something we should fix.

**Comment by FredrikKarlssonSpeech** [comment]
Seems to work.
