### ISSUE TITLE
Add correct recognition for Matlab scripts in README

### ISSUE THREAD

**Issue by TomasSkotare** [humlab-speech/visible-speech-deployment#132]
Source:
https://www.darth-group.com/software

[Voice Analysis Toolbox (version 1.0)](https://www.dropbox.com/s/5iy11htw3arv0py/VoiceAnalysisToolbox.zip?dl=0)[](https://www.dropbox.com/s/5iy11htw3arv0py/VoiceAnalysisToolbox.zip?dl=0)
This toolbox presents a number of speech signal processing algorithms, aiming at the objective characterization of voice, and in particular the assessment of voice disorders. These algorithms are mainly directed at quantifying amplitude (shimmer variants), frequency (jitter variants) and increased noise (signal-to-noise measures). Note that the toolbox has been developed and has only been validated in settings with the sustained vowel /a/. The algorithmic tools herein may be generalizable to other sustained vowels, but they are definitely not appropriate for conversational speech. The toolbox was developed in a series of journal and conference studies, and the most important are highlighted below. Please include the following citations if you use this toolbox in your work:

​

[A. Tsanas, M.A. Little, P.E. McSharry, L.O. Ramig: “New nonlinear markers and insights into speech signal degradation for effective tracking of Parkinson’s disease symptom severity”, International Symposium on Nonlinear Theory and its Applications (NOLTA), pp. 457-460, Krakow, Poland, 5-8 September 2010](https://www.dropbox.com/s/t6rtygxnrma8af4/NOLTA2010.pdf?dl=0)

[A. Tsanas, M.A. Little, P.E. McSharry, L.O. Ramig: "Nonlinear speech analysis algorithms mapped to a standard metric achieve clinically useful quantification of average Parkinson’s disease symptom severity", Journal of the Royal Society Interface, Vol. 8, pp. 842-855, June 2011](https://www.dropbox.com/s/6ld3gqlipj2qoc5/JRSI2011.pdf?dl=0)

[A. Tsanas: Accurate telemonitoring of Parkinson’s disease symptom severity using nonlinear speech signal processing and statistical machine learning, D.Phil. thesis, Oxford Centre for Industrial and Applied Mathematics, University of Oxford, UK, 2012](https://www.dropbox.com/s/qnkfqmqonpvh9wi/DPhil%20thesis.pdf?dl=0)

**Comment by FredrikKarlssonSpeech** [comment]
FIxed here https://github.com/humlab-speech/superassp/blob/master/man/voice_analysis.Rd
