### ISSUE TITLE
Add Matomo install instructions to Readme?

### ISSUE THREAD

**Issue by TomasSkotare** [humlab-speech/visible-speech-deployment#133]
Discuss if required, as it will be highly use dependant (and not required to use the system).

This includes:
* Setting up the website in Matomo
* Ensuring the forwards work
* Possibly including log data

Currently Matomo is installed regardless when running the system, but will be inactive.

**Comment by johanvonboer** [comment]
I would vote for skipping this. Matomo is important to us but probably not to other people.

**Comment by TomasSkotare** [comment]
I agree, but should we then remove Matomo from the default running containers (by commending out those lines)?
