### ISSUE TITLE
Keycloak crashed

### ISSUE THREAD

**Issue by FredrikKarlssonSpeech** [humlab-speech/visible-speech-deployment#135]
![Skärmavbild 2022-05-02 kl  09 23 30](https://user-images.githubusercontent.com/200246/166199167-1787533a-22d6-4132-ac04-01386d4070b6.png)

**Comment by johanvonboer** [comment]
Still not sure what caused this, but have updated Keycloak from 13.0.1 => 16.1.1

**Comment by FredrikKarlssonSpeech** [comment]
Ok. Seems to work now.
