### ISSUE TITLE
Problems with the authentication flows

### ISSUE THREAD

**Issue by johanvonboer** [humlab-speech/visible-speech-deployment#142]
This is perhaps mostly a note-to-self, but it could be a serious concern:

Trying to implement authentication against the KTH IdP has revealed a problem with our current setup; The IdPs we want to authenticate against, which was previously just Umu, retrieves their information (our sp-metadata) about our service from SWAMID, this describes, among other things, which endpoints/URLs to use.

This becomes a problem with multiple IdPs using the same metadata/description of our service since Keycloak creates separate endpoints for each IdP. For example, the Umu-IdP should post their SAML responsens to the endpoint: https://idp.visp.humlab.umu.se/auth/realms/visp/broker/Umu-id/endpoint but this is obviously not valid for KTH.

Solution 1:
We ask each IdP to manually import our metadata which will be custom tailored for them, instead of fetching it from SWAMID. This is in my opinion a very unappealing solution since it's just a hassle, both for us and for the IdPs we wish to interact with.

Solution 2:
We ditch Keycloak and switch over to just running Shibboleth with SeamlessAccess service discovery. This will also automatically integrate our service with a very large amount of all the universities in the world (if we opt-in to have our service registered in edu-gain). The downside with is that we can no longer create our own local accounts, however, this may not be much of a problem considering that, at least here at UMU, it seems to be possible to create accounts for external non-affiliated persons if need be.

Solution 3:
Find a way to have generic endpoints in Keycloak, perhaps it is possible somehow?

**Comment by FredrikKarlssonSpeech** [comment]
Seems to work..?

**Comment by johanvonboer** [comment]
It works great for the main portal site, but *someone* failed to account for the fact that gitlab does not support IdP discovery services, which means gitlab can't use swamid for authentication since it needs to be tied to a single IdP. However I think I have a solution for it and I'm working on it.
