### ISSUE TITLE
not working gitlab links

### ISSUE THREAD

**Issue by FredrikKarlssonSpeech** [humlab-speech/visible-speech-deployment#143]
Gitlab links not working anymore in the web interface.

**Comment by johanvonboer** [comment]
Fixed

**Comment by FredrikKarlssonSpeech** [comment]
No, not working properly yet.

I tried to use one of the links (Repository) and got this

![Skärmavbild 2022-09-01 kl  10 48 14](https://user-images.githubusercontent.com/200246/187878093-fb5f7df9-bfd6-4dd1-9f56-cc552308f8d4.png)

**Comment by johanvonboer** [comment]
Strange, but fixed.

Known issues:
1. Sometimes you end up in a redirect loop when authenticating against gitlab.
2. Logout is not expected to work at this time, but I'm hopeful about getting it to work, it's just a matter of being able to spend the required amount of time on it.

**Comment by FredrikKarlssonSpeech** [comment]
Works now. The authentication loop is still there the first time, but the links work the second time you click on one of them.
