### ISSUE TITLE
Re-activate 2-factor auth

### ISSUE THREAD

**Issue by johanvonboer** [humlab-speech/visible-speech-deployment#154]
I have emailed ITS about this, no reply yet.

**Comment by FredrikKarlssonSpeech** [comment]
Still no reply from ITS @johanvonboer ?

**Comment by johanvonboer** [comment]
Yes, we are emailing back and forth, it has turned out to be a little bit more complicated, because the proper way to do this (at the moment - based on how things are) is for us to do a little bit of what they call "signaling" by passing a request argument, rather than they hardcoding our metadata, and I need to figure out how to do that. I especially don't see how that will be compatible with the discovery service seamlessacess, but according to ITS it is, and this should be possible to do with a shibboleth sp such as ours, so I just need to do some more investigating regarding this...

**Comment by johanvonboer** [comment]
I figured it out, and yes it is compatible with seamlessaccess, BUT, it breaks compatibility with everyone else, such as KTH and SU. To make matters even worse it doesn't even guarantee that MFA really was used for the login since a SAML auth request can be forged without this signaling and UmU's IdP doesn't currently send back the correct "authContext" which designates whether MFA was used or not, so we have no way of knowing if MFA was really used for this login, turning the whole thing into a security theatre.

We'll see how we move forward, still emailing with ITS...

**Comment by johanvonboer** [comment]
We now have forced MFA via the UmU IdP again.
