### ISSUE TITLE
Going from git actions within the container to saving the container from outside does not work well

### ISSUE THREAD

**Issue by FredrikKarlssonSpeech** [humlab-speech/visible-speech-deployment#164]
I may only add, commit and push changes to the repository from within the container if I set `user.email` and `user.name`.
I am not sure it matters but setting the name to the gitlab user name works. Not sure the email matters.

However, once I have made git work within the container, trying to "Save" it from outside using the save button  results in an error message:

![Skärmavbild 2022-11-07 kl  20 55 41](https://user-images.githubusercontent.com/200246/200403218-0edf27b9-a38d-49e8-a8b0-acbf378b45cd.png)

and it seems nothing it committed (though I have not verified that part thoroughly).

**Comment by johanvonboer** [comment]
Setting the username and email is normal for now, the container-agent does this for every operation as well, but we could of course look into getting around that by setting that up when the container is launched.

The --local thing might be related to the ownership issue. If you're in jupyter, check that all the files in the git repo is owned by jovyan.

**Comment by FredrikKarlssonSpeech** [comment]
Ok, not actually a fault of the VISP then, so closing.
