### ISSUE TITLE
Improve loading speed of sounds and signals in the webapp

### ISSUE THREAD

**Issue by FredrikKarlssonSpeech** [humlab-speech/visible-speech-deployment#167]
In the discussion of FLAC support in emuR Web app

https://github.com/IPS-LMU/EMU-webApp/issues/328

the quick proposed interim fix is to start looking at server compression to gzip before sending content.
"Content-Encoding: gzip"

Do we send files to the webapp this way?

**Comment by johanvonboer** [comment]
Yes, the wav files sent to the emu-webapp seems to be compressed by the webserver:

![image](https://user-images.githubusercontent.com/34707290/202436993-40c39a6d-b670-4f11-9e7e-acf83c85b9d6.png)

**Comment by FredrikKarlssonSpeech** [comment]
Great!!
