### ISSUE TITLE
Can't build images due to reindeer error

### ISSUE THREAD

**Issue by johanvonboer** [humlab-speech/visible-speech-deployment#169]
Can't build this image: https://github.com/humlab-speech/visible-speech-deployment/blob/master/docker/session-manager/operations-session/Dockerfile

Because:
![image](https://user-images.githubusercontent.com/34707290/203314927-f4ab1ce5-86d3-4104-828f-a4e6140278cc.png)

Is this an error with reindeer or do I need to fix the image somehow?

**Comment by FredrikKarlssonSpeech** [comment]
Sure. Ive worked in a branch for some time now so this is a bit old code, but the code does not seem to be the issue actually.
I can install the package fine, just not generate docs. Will look into why.

**Comment by FredrikKarlssonSpeech** [comment]
An object method that I introduced in superassp replace the one in wrassp seems to have introduced friction between superassp and the main branch of reindeer. Never noticed since I am in a different branch for most work in reindeer.

@johanvonboer The packages should at least build now.
