### ISSUE TITLE
Logout problems

### ISSUE THREAD

**Issue by johanvonboer** [humlab-speech/visible-speech-deployment#170]
There seems to be multiple problems with the logout.

1. I sometimes get this, but not always, it's not consistent:
![image](https://user-images.githubusercontent.com/34707290/203569660-c9e78da0-0949-43f1-adab-468492c465c9.png)

2. The logout sometimes fails at the UmU IdP with another error message that I don't have a screenshot of atm.

3. The logout sometimes doesn't redirect to the IdP at all!

Then there's the gitlab logout which already exists as a separate issue.

**Comment by johanvonboer** [comment]
Here's an example of failing at the IdP:
![image](https://user-images.githubusercontent.com/34707290/205056608-7a83f4de-a00c-40d6-8052-bb3c2d187f29.png)

**Comment by FredrikKarlssonSpeech** [comment]
Seems fixed for now.
