### ISSUE TITLE
VISP demo: web speech recorder links not working yet

### ISSUE THREAD

**Issue by FredrikKarlssonSpeech** [humlab-speech/visible-speech-deployment#198]
I could now crease a session that is meant to be filled by web speech recorder, but the link is not functional right now.

<img width="1498" alt="Skärmavbild 2024-03-04 kl  11 18 59" src="https://github.com/humlab-speech/visible-speech-deployment/assets/200246/779cd73a-208a-4e35-9ee2-59bf2030889b">

**Comment by johanvonboer** [comment]
Fixed. I had simply completely forgotten about webspeechrecorder and so the server for it was not even running, but it is now.
