### ISSUE TITLE
GitLab personal access tokens problems

### ISSUE THREAD

**Issue by johanvonboer** [humlab-speech/visible-speech-deployment#20]
The GitLab handling of personal access tokens causes some problems for us, I go into detail here: https://forum.gitlab.com/t/deleting-personal-access-tokens-via-the-api/50382

But the TLDR is that personal access tokens can't be deleted from the API, which means it's not sustainable to create a new PAT per session, as we would like to do. Instead we're going to have to find a less ideal way around this.

**Comment by johanvonboer** [comment]
...and a less ideal way has indeed been found and implemented! Which is that we now store the PATs in a MongoDB. This should be reasonable secure, but it's hopefully only a temporary solution until GitLab patches this flaw, so I'll leave this issue open.

**Comment by TomasSkotare** [comment]
The system is no longer based on GitLab, so this can be closed.
