### ISSUE TITLE
Interpreting Git output

### ISSUE THREAD

**Issue by johanvonboer** [humlab-speech/visible-speech-deployment#32]
The way we currently perform commits & pushes from a container into Gitlab is via executing shell scripts and then interpreting the text output to see if the push was successful or not. This is terrible since the text output may change between Git versions. We should have a better system for remote controlling Git, but currently not sure what. Needs to be investigated at some point.

**Comment by TomasSkotare** [comment]
As we move away from GitLab, this will not be relevant going forward
