### ISSUE TITLE
"At rest" data encryption

### ISSUE THREAD

**Issue by TomasSkotare** [humlab-speech/visible-speech-deployment#42]
Encrypt the data while at rest, i.e. not in transit over the internet.

This option has been discussed previously, however the current options incur a performance penalty, and can also cause issues due to the number of open files allowed in such a system.

**Comment by FredrikKarlssonSpeech** [comment]
What is the solution?  How can one tell when the media file store is emptied?
Can I assume that the use of "Clear" as a term for "Disconnecting to the server" actually means that that is when the media file store is emptied?

**Comment by TomasSkotare** [comment]
As I do not believe this will add a relevant upgrade in security, and the risk of losing the keys to the data is much larger than any other risk, I believe we can safely drop this issue.
