### ISSUE TITLE
Make new logo / logos for VISP

### ISSUE THREAD

**Issue by FredrikKarlssonSpeech** [humlab-speech/visible-speech-deployment#58]
"Visualiserat Språk"
"Visible Speech"

**Comment by johanvonboer** [comment]
Kajsa sent me some updated logos just before she went on holiday and maternity leave, perhaps we could go through them during a meeting.

**Comment by FredrikKarlssonSpeech** [comment]
Do we have them in the UmU color scheme now? Then we could close this issue?

**Comment by johanvonboer** [comment]
Yes, I have updated the site
