### ISSUE TITLE
No feedback when creating a project (or is it not possible?)

### ISSUE THREAD

**Issue by FredrikKarlssonSpeech** [humlab-speech/visible-speech-deployment#66]
If you create a new project in the interface, attach some files and click "Create project" - nothing happens.
No feedback and no progress bar. Does something happen?

**Comment by FredrikKarlssonSpeech** [comment]
THe issue is there regardless of whether an EmuDB is set up or not.

**Comment by johanvonboer** [comment]
Fixed now
