### ISSUE TITLE
Routing gets confused when starting more than one docker container for a project

### ISSUE THREAD

**Issue by TomasSkotare** [humlab-speech/visible-speech-deployment#67]
To reproduce:
Start either r-studio or jupyter notebooks. Remember which one was first.
Start the other, e.g. if you first started juputer, now start r-studio and the other way around.

Expected behavior: Both tabs work independently.

Actual behavior:
Refresh both tabs. The tab that was started first will be confused and redirect to the other. Both are still running and can be reached again by clicking the button from the main interface, but the other is then not available.

**Comment by johanvonboer** [comment]
This could be fixed, and perhaps it should be in the future, but the current plan is to not support letting the user have multiple applications/tabs running anyway, so I'll just mark this as "won't fix" for now.

**Comment by johanvonboer** [comment]
This is no longer an issue since we only allow one application running at a time
