### ISSUE TITLE
Add perspectives in Emu-webApp

### ISSUE THREAD

**Issue by liasam92** [humlab-speech/visible-speech-deployment#70]
When the user creates a new project, three perspectives are added to Emu-webApp:
1. default (which is always added when calling `create_emuDB`
2. Formants
3. Formants+F0

For this workflow, we need to include Fredrik's new formant tracks calculations.
R-code:

1. **Fredrik's function** using gender and age as parameters for calculating formant tracks 
(**EmuR:** `add_ssffTrackDefinition(dbHandle, name = "FORMANTS", onTheFlyFunctionName = "forest")`)
2. **EmuR:** `add_ssffTrackDefinition(dbHandle, name = "F0", onTheFlyFunctionName = "ksvF0")`
3.  **Add formant perspective** 
`add_perspective(dbHandle, "Formants")`
`set_levelCanvasesOrder(dbHandle, perspectiveName = "Formants", order = c(" #Phonetic"))`
4. **Add formant+fo perspective**
  `add_perspective(dbHandle, "Formants+F0")`
`set_levelCanvasesOrder(dbHandle, perspectiveName = "Formants+F0", order = c("Phonetic"))`
5. **Add following to DBconfig.json** (bold = add, italic = should already be in DBconfig)
    _{
        "name": "Formants",
        "signalCanvases": {
          "order": [
            "OSCI",
            "SPEC"
          ],
          "assign": [_
            **{
              "signalCanvasName": "SPEC",
              "ssffTrackName": "FORMANTS"
            }**
         _ ],
          "contourLims": []
        },
        "levelCanvases": {
          "order": [
            "Phonetic"
          ]
        },
        "twoDimCanvases": {
          "order": []
        }
      },
      {
        "name": "Formants+F0",
        "signalCanvases": {
          "order": [
            "OSCI",
            "SPEC"**,
            "F0"**
          ],
          "assign": [_
            **{
              "signalCanvasName": "SPEC",
              "ssffTrackName": "FORMANTS"
            }**
          _],
          "contourLims": []
        },
        "levelCanvases": {
          "order": [
            "Phonetics"
          ]
        },
        "twoDimCanvases": {
          "order": []
        }
      }
    ]_

**Comment by FredrikKarlssonSpeech** [comment]
Implmented.
