### ISSUE TITLE
A mechanism for keeping the server alive is needed?

### ISSUE THREAD

**Issue by FredrikKarlssonSpeech** [humlab-speech/visible-speech-deployment#79]
The server is down now, and that highlights the fact that we need to have routines in place on how to restart it if it goes down.

**Comment by johanvonboer** [comment]
Brought it back up now. I'm guessing ITS rebooted it since not a single docker container was running. Agree on the need of restarting routines!

**Comment by johanvonboer** [comment]
Fixed, cluster of services will now auto restart when server is rebooted
