### ISSUE TITLE
addTrackDefinitions problems

### ISSUE THREAD

**Issue by johanvonboer** [humlab-speech/visible-speech-deployment#81]
When gender is null:

`session-manager_1  | 2021-08-26 15:20:19 [INFO] Executing command in session container: /usr/bin/node /container-agent/main.js emudb-track-definitions  with ENV: ANNOT_LEVELS=W3sibmFtZSI6IldvcmQiLCJ0eXBlIjoiSVRFTSJ9LHsibmFtZSI6IlBob25ldGljIiwidHlwZSI6IlNFR01FTlQifV0= PROJECT_PATH=/home/project-setup UPLOAD_PATH=/home/uploads EMUDB_SESSIONS=W3siaWQiOiJzZXNzaW9uLWw1UHJ4dU5Xb0k3dl9qMnVSREdHSSIsIm5hbWUiOiJTcGVha2VyXzEiLCJzcGVha2VyR2VuZGVyIjpudWxsLCJzcGVha2VyQWdlIjozNSwiZmlsZXMiOlt7InVwbG9hZENvbXBsZXRlIjp0cnVlfV19XQ==
session-manager_1  | 2021-08-26 15:20:21 [INFO] Stream data: �{"code":200,"body":{"stdout":"INFO: Checking if cache needs update for 1 sessions and 1 bundles ...\nINFO: Pe
rforming precheck and calculating checksums (== MD5 sums) for _annot.json files ...\nINFO: Nothing to update!\n","stderr":"Error in `*tmp*`[[jj]] : subscript out of bounds\nCalls: add_trackDefinition ... get_metadata -> export_metadata -> [<- -> [<-.data.frame\nExecution halted\n","error":{"killed":false,"code":1,"signal":null,"cmd":"R -s -f /container-agent/scripts/addTrackDefinitions.R"}}}`

When gender is specifed:

`session-manager_1  | 2021-08-26 15:21:25 [INFO] Executing command in session container: /usr/bin/node /container-agent/main.js emudb-track-definitions  with ENV: ANNOT_LEVELS=W3sibmFtZSI6IldvcmQiLCJ0eXBlIjoiSVRFTSJ9LHsibmFtZSI6IlBob25ldGljIiwidHlwZSI6IlNFR01FTlQifV0= PROJECT_PATH=/home/project-setup UPLOAD_PATH=/home/uploads EMUDB_SESSIONS=W3siaWQiOiJzZXNzaW9uLThwZnBkbzFId05KOFNhWXZwODVJXyIsIm5hbWUiOiJTcGVha2VyXzEiLCJzcGVha2VyR2VuZGVyIjoiRmVtYWxlIiwic3BlYWtlckFnZSI6MzUsImZpbGVzIjpbeyJ1cGxvYWRDb21wbGV0ZSI6dHJ1ZX1dfV0=
session-manager_1  | 2021-08-26 15:21:28 [INFO] Stream data: I{"code":200,"body":{"stdout":"INFO: Checking if cache needs update for 1 sessions and 1 bundles ...\nINFO: Pe
rforming precheck and calculating checksums (== MD5 sums) for _annot.json files ...\nINFO: Nothing to update!\n\r  |
                   \r  |                                                                      |   0%\r  |
        \r  |======================================================================| 100%\n","stderr":"Applying the function 'forest' to all .wav files for which a signal track file (.) does not exist.\n\nError in dyn.load(file, DLLpath = DLLpath, ...) : \n  unable to load shared object '/usr/local/lib/R/site-library/git2r/libs/git2r.so':\n  libgit2.so.28: cannot open shared object file: No such file or directory\nCalls: add_trackDefinition ... getNamespace -> loadNamespace -> library.dynam -> dyn.load\nExecution
halted\n","error":{"killed":false,"code":1,"signal":null,"cmd":"R -s -f /container-agent/scripts/addTrackDefinitions.R"}}}`

**Comment by FredrikKarlssonSpeech** [comment]
I just pushed a version with a very explicit file-level check on the availability of the shared library. I noticed this in the error message above

    unable to load shared object '/usr/local/lib/R/site-library/git2r/libs/git2r.so':\n libgit2.so.28: cannot open shared object file: No such file or directory\n

Maybe this is a symlink error? (I only have a libgit2.so on my system.)

**Comment by FredrikKarlssonSpeech** [comment]
The issue appears to not be there anymore, and signal files are still added to the git repository

@johanvonboer :
* Does this mean that they are added to git by code executed elsewhere? 
* Is the add_ssffTrackDefinition function used now, or the add_trackDefinition? 
  (I will continue to investigate this in the code).

**Comment by johanvonboer** [comment]
Sorry I forgot to mention that I rebuilt the session container images this morning and thus it pulled in your latest changes in reindeer, since that was done it seems to work.

Here's the relevant log output from the latest project creation (which I guess must be the last project you created):

`session-manager_1  | 2021-09-01 11:37:55 [INFO] Executing command in session container: /usr/bin/node /container-agent/main.js emudb-track-definitions  with ENV: ANNOT_LEVELS=W3sibmFtZSI6IldvcmQiLCJ0eXBlIjoiSVRFTSJ9LHsibmFtZSI6IlBob25ldGljIiwidHlwZSI6IlNFR01FTlQifV0= PROJECT_PATH=/home/project-setup UPLOAD_PATH=/home/uploads EMUDB_SESSIONS=W3siaWQiOiJzZXNzaW9uLXRxWTVTQnM2eUxldHZFSGF4YWx6eiIsIm5hbWUiOiJTcGVha2VyXzEiLCJzcGVha2VyR2VuZGVyIjoiRmVtYWxlIiwic3BlYWtlckFnZSI6MzUsImZpbGVzIjpbeyJ1cGxvYWRDb21wbGV0ZSI6dHJ1ZX1dfSx7ImlkIjoic2Vzc2lvbi1aUUpFUE5GVElqOFRsTjRQMkVKRVQiLCJuYW1lIjoiU3BlYWtlcl8yIiwic3BlYWtlckdlbmRlciI6Ik1hbGUiLCJzcGVha2VyQWdlIjozNSwiZmlsZXMiOlt7InVwbG9hZENvbXBsZXRlIjp0cnVlfV19XQ==
session-manager_1  | 2021-09-01 11:37:57 [INFO] Stream data: �{"code":200,"body":{"stdout":"INFO: Checking if cache needs update for 2 sessions and 2 bundles ...\nINFO: Performing precheck and calculating checksums
 (== MD5 sums) for _annot.json files ...\nINFO: Nothing to update!\n\r  |                                                                            \r  |
        |   0%\r  |                                                                            \r  |===================================                                   |  50%\r  |
                                         \r  |======================================================================| 100%\n\r  |                                                                            \r  |
                                                                |   0%\r  |                                                                            \r  |===================================
          |  50%\r  |                                                                            \r  |======================================================================| 100%\n","stderr":"Applying the function 'forest' to all .wav files for which a signal track file (.) does not exist.\n\nApplying the function 'ksvF0' to all .wav files for which a signal track file (.) does not exist.\n\n","error":null}}`

And that looks good to me, so I guess this is fixed now...?

About your questions
`Does this mean that they are added to git by code executed elsewhere?`
I'm not completely sure I understand what you mean here, are you saying that it should NOT be working as it is now because all you did was to add a file-level check on the .so file so it should still fail but only more gracefully? And therefore you are asking if some other code is creating the track files? If that's the question :) then the answer is no, I could investigate further, but I'm pretty sure there's nothing else other than calling that R script with the add_trackDefinition call in it that could be creating those files.

`Is the add_ssffTrackDefinition function used now, or the add_trackDefinition?`
It's add_trackDefinition. If it were the ssff-version then the command to the container-agent would be emudb-ssff-track-definitions but since it's emudb-track-definitions we can be sure it's that one

**Comment by FredrikKarlssonSpeech** [comment]
"About your questions
    Does this mean that they are added to git by code executed elsewhere?
    I'm not completely sure I understand what you mean here, are you saying that it should NOT be working as it is now because all you did was to add a file-level check on the .so file so it should still fail but only more gracefully? And therefore you are asking if some other code is creating the track files? If that's the question :) then the answer is no, I could investigate further, but I'm pretty sure there's nothing else other than calling that R script with the add_trackDefinition call in it that could be creating those files."

My logic was that when _new_ tracks are created, what should happen is:
1) make new track files in the database. 
2) Register the new kind of tracks in the Emu database config file.
3) Check whether the Emu database is part of a git repo
  * if it is, then add + commit the created track files to the repo, as otherwise they would be registered in the Emu config file but not sync:ed back to Gitlab when the user Saves + Quits the container.

BUT, if "Save" actually means that also all files in the Emu database that are not part of the git repo will also be added + commited to the repo before the repo is pushed to Gitlab, then the R code that is creating these problems is not acually needed and may be removed (along with the git2r dependency for "reindeer").

So, could "Save" actually be described as "Add and commit all not added files to the repo and push everything to Gitlab"? :-)

**Comment by FredrikKarlssonSpeech** [comment]
Seems fixed.
