### ISSUE TITLE
Deactivate "Rstudio" when a Jupyter container is launched, and vice versa. 

### ISSUE THREAD

**Issue by FredrikKarlssonSpeech** [humlab-speech/visible-speech-deployment#83]

**Comment by johanvonboer** [comment]
Fixed

**Comment by FredrikKarlssonSpeech** [comment]
If I create a new project, all buttons are now dimmed in the interface for that project once just created.
The project I had before looked ok. (here is a screenshot)

![Skärmavbild 2021-09-01 kl  11 32 19](https://user-images.githubusercontent.com/200246/131648718-e280894e-94c5-48ec-b7c7-1689d30e3fe7.png)
And i cannot launch tools for the newly created project: 
![Skärmavbild 2021-09-01 kl  11 32 27](https://user-images.githubusercontent.com/200246/131648825-2192d8ba-08a4-48e0-b64e-dc9cedfec192.png)

It seems that this happens for all new projects:

![Skärmavbild 2021-09-01 kl  11 38 18](https://user-images.githubusercontent.com/200246/131649189-a905622f-d912-4130-b3fa-012892d12762.png)

A reload fixes the issue and also starting any tool for a different project first.

**Comment by johanvonboer** [comment]
Yes, I discovered this earlier today, but thanks for the good bug report! :)
