### ISSUE TITLE
Handle logging in a better way

### ISSUE THREAD

**Issue by johanvonboer** [humlab-speech/visible-speech-deployment#84]
As it is now we have multiple services logging various kinds of data. There's the webserver logging requests, the session-manager logging activity, keycloak logging authentication, gitlab logging events, etc.

We should probably:

1. Make sure suspicious activity is logged. Such as multiple failed authentication attempts and attempts to access endpoints outside the normal flow. This requires going through a lot of code in the session-manager and making sure all the other of-the-shelf services are configured appropriately.

2. Feed all the logs into a central manager, e.g. Logstash, Nagios or similar and set up automated alerts in this central manager. Would be great if this manager also had some sort of machine learning so that it could automatically detect unusual activity patterns and alert on them.

3. Implement automatic banning of detected brute force attacks. Perhaps ITS can do some of this even before that traffic reaches our server.

I don't have any finished answers right now since all of this requires more research, I'm just creating this issue so we can start having a discussion around it.

**Comment by FredrikKarlssonSpeech** [comment]
Take advantage of ITS logging store.

**Comment by FredrikKarlssonSpeech** [comment]
we can delay this until we get all information in week 48.
