### ISSUE TITLE
ssff-files are not created

### ISSUE THREAD

**Issue by liasam92** [humlab-speech/visible-speech-deployment#94]
It seems like this issue might have been resolved @ #93 
When creating a new emuDB, wav files are imported; however, no ssff files are created.
Since we need ssff-files to show the different perspectives in emu-webapp, we get the same error message when loading emu-webapp as before ( @ #93 ):
_"Error validating / checking DBconfig: "Error in EMUwebAppConfig/perspectives/signalCanvases/assign! References to undefined ssffTracks are present. Following ssffTracks are not defined: FORMANTS"_

**Comment by FredrikKarlssonSpeech** [comment]
@johanvonboer 

Please update the reindeer package from github, and try using import_recordings instead of emuR::import_mediafiles.

* The new function always just imports one sound channel.
* You can also specify an optional EGG channel, which will be stored in an .egg file.

**Comment by FredrikKarlssonSpeech** [comment]
@johanvonboer 

I just pushed a new version with revised parameter matching code. The issue, at least one of them, were in how windowSize were specified in the collection of default settings and how that caused the parameters to be selected.

**Comment by johanvonboer** [comment]
I have now updated the production site with these fixes:

* Latest Reindeer version pulled in
* Using import_recordings function instead of import_mediaFiles
* Always converting speakerAge metadata variable to integer
