### ISSUE TITLE
Bug in perspectives

### ISSUE THREAD

**Issue by liasam92** [humlab-speech/visible-speech-deployment#95]
Perspectives "Formants" and "Formants+F0" are not set up properly.
The following (marked bold) should be added to dbconfig (Note that "Phonetic" should be replaced by all annotation levels of type "SEGMENT") 

{
        "name": "Formants",
        "signalCanvases": {
          "order": [
            "OSCI",
            "SPEC"
          ],
          "assign": [
            {
              "signalCanvasName": "SPEC",
              "ssffTrackName": "FORMANTS"
            }
          ],
          "contourLims": []
        },
        "levelCanvases": {
          "order": [**"Phonetic"**]
        },
        "twoDimCanvases": {
          "order": []
        }
      },
      {
        "name": "Formants+F0",
        "signalCanvases": {
          "order": [
            "OSCI",
            "SPEC"**,
              "F0"**
          ],
          "assign": [
            {
              "signalCanvasName": "SPEC",
              "ssffTrackName": "FORMANTS"
            }
          ],
          "contourLims": []
        },
        "levelCanvases": {
          "order": [**"Phonetic"**]
        },
        "twoDimCanvases": {
          "order": []
        }
      }

**Comment by johanvonboer** [comment]
I think this is fixed now... @liasam92 could you check/test that it seems to be right and that I didn't miss anything?

**Comment by liasam92** [comment]
The F0 canvas is always visible. It should only be visible in the "Formants+F0" perspective.
See code below
```
"name": "Formants+F0",
"signalCanvases": {
"order": [
"OSCI",
"SPEC",
"F0"
],
```

**Comment by johanvonboer** [comment]
Fixed
